### ISSUE TITLE
Вопросы / идеи для разговора с iggisv9t

### ISSUE THREAD

**Issue by gad26032** [ods-ai-ml4sg/proj_news_viz#102]
Идеология:
- Глобальные цели?
- Как выглядит пайплайн?
- Есть ли бюджет на сервера(БД)?
- Где храните данные?

Замечания:
- Есть ли тестирование?
- Нужен простой скрипт для того что бы сетапить окружение.
  - Или хотя бы описание как правильно засетапить
  - Какой менеджер пакетов?
    - Conda(Anaconda)?
    - pip?
- Запускаемые скрипты для проброса параметров использовать `argparse`.
- Какя БД?
  - SQL ?
    - Судя по коду используете SQL
    - Недостаток в том что нужна схема.
  - Mongo ?
    - Преимущество в том что схема агностик.
    - Доступ к данным можно организовать с помощью `Reader` классов.
- Пробовали ли запускать на больших датасетах?
  - Не отжирает ли память?
- Jupytext мастхев. Так проще искать зависимости, рефакторить и мерджить ноутбуки.

Полезное:
- Elasticsearch
- Jupytext
- `argparse`
- MongoDB

**Comment by Avenon** [comment]
Отвечу за свою часть, т.к. я занимался пайплайном на luigi.
> Как выглядит пайплайн?

Пайплайн сделан на luigi, описание его тут: [Схема и описание пайплайна](https://github.com/ods-ai-ml4sg/proj_news_viz/wiki/%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0-%D0%B8-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%91%D0%94-%D0%B8-%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%B0-%D0%BD%D0%B0-luigi#process)

> Где храните данные?

Сейчас доступные датасеты лежат в releases: [](https://github.com/ods-ai-ml4sg/proj_news_viz/wiki/Available-datasets)
Также данные можно загрузить в БД

> Нужен простой скрипт для того что бы сетапить окружение

Я делал целую инструкцию о том, как развернуть, проверить  и загрузить данные в пайплайн: [Установка окружения и работа с luigi](https://github.com/ods-ai-ml4sg/proj_news_viz/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BE%D0%BA%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F-%D0%91%D0%94-%D0%B8-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-luigi)

> Какя БД?
> Нужна схема

Postgres SQL. Схему БД (логическую и физическую) я рисовал и описывал тут: [Структура и работа с БД и описание процесса на luigi](https://github.com/ods-ai-ml4sg/proj_news_viz/wiki/%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0-%D0%B8-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%91%D0%94-%D0%B8-%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%B0-%D0%BD%D0%B0-luigi#process)

> Пробовали ли запускать на больших датасетах?
> Не отжирает ли память?
Да, пробовал. Минимальный датасет был rt (106000 новостей, 225 мб), максимальный - tass (3 гигабайте). Код долго оптимизировал, т.к. память выжиралась, сейчас работает без утечек памяти, т.к. использую батчи. Проверено с помощью htop. Также была проблема, что на моих ноутах запускался корректно (8 и 16 гб), а на сервере вылетало из-за нехватки памяти (там 4гб), как итог код был оптимизирован, сейчас работает.

Допонительная инфа:
[Как загрузить датасеты в базу](https://github.com/ods-ai-ml4sg/proj_news_viz/wiki/%D0%9F%D1%80%D0%B5%D0%B4%D0%B2%D0%B0%D1%80%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-%D1%81-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8)

Если будут вопросы по пайплайну на luigi, то можешь также мне адресовывать, т.к. я им занимался.
