### ISSUE TITLE
Препроцессинг удаляет иностранные слова из новости

### ISSUE THREAD

**Issue by Avenon** [ods-ai-ml4sg/proj_news_viz#106]
Сегодня обратил внимание, на то, что имеющийся препроцессинг удаляет иностранные слова из новости. Т.е. слова, которые написаны англоязычными символами.
Пример:

```
clean_text('microsoft официально представило новый xbox на новой платформе')
>>> 'официально представило новый на новой платформе'
```
Таким образом теряется много информации, особенно если в новости есть умоминание иностранного бренда, компании, продукта. 
Соответственно новость становится не информативной, как видно из примера не понятно становится о чем речь.
Варианты решения:
1) Переделать регулярку в процессинге таким образом, чтобы удалялись одичные иностранные символы, а символы больше одного знака, заключенные в пробелы не трогать
2) Может ner какой-то подключит, чтобы собирать такие названия и выделять их в отдельный словарь.

**Comment by vtrokhymenko** [comment]
да, вот [тут](https://github.com/ods-ai-ml4sg/proj_news_viz/blob/73b34b847645f8f218de275d091add2040541602/nlp/news_viz/data/preprocessing_tools.py#L46) мы оставляем исключительно кириллицу

да, те решения, которые ты предложил, все подходят
важно только ответить на вопрос где именно мы будем это использовать и потом уже придумать решение

**Comment by Avenon** [comment]
Да, я об этой строке и говорю, просто думал, что она одиночные символы удаляет, а решил проверить и вот. 
Просто мне кажется, что удалив иностранные слова, мы теряем часть информации по новости, соответственно темы могут получиться не информативными. 
Плюс опять же, у меня в пайплане новость преобразовывается и записывается в новую таблицу уже токенизированной и получается, что часть данных мы теряем. Это и смущает.

**Comment by vtrokhymenko** [comment]
все ты правильно говоришь, провафлили этот момент

**Comment by iggisv9t** [comment]
Я так понял, #109 это исправляет.
