### ISSUE TITLE
Запилить пайплайн

### ISSUE THREAD

**Issue by iggisv9t** [ods-ai-ml4sg/proj_news_viz#108]
Задача описана сто раз в разных местах. Пусть теперь будет единое место здесь.

1. Понижаем порог входа: временно забываем про postgres. Данные и отдельные этапы процессинга пусть будут либо файликами, либо в локальной БД на sqlite. На постгру переедем, когда всё остальное будет работать.
2. Всё пилим на luigi потому что он простой как пень и делает что нам надо.
3. На парсеры и пауки пока забиваем. Сначала разделаемся один раз на данных, которые есть, потом будет налаживать регулярные обновления.

Что нужно сделать:
1. Штуку, которая берёт сырые новости и пишет предобработанные.
    - В терминах луиджи таски: у нас есть файлы (или записи в БД) на входе, для каждого файла должен быть output, допустим файл с таким же названием в директории processed. Таска запускается, смотрит во входную директорию, смотрит какие выходы уже готовы и делает те, которые не готовы.
2. Штуку, которая берёт очищенный текст, обученную модель и делает классификацию на рубрики.
    - Таск смотрит всё, что есть на входе, считает что для каждого из них должен быть выход, допустим в очередной директории classified или в отдельной табличке в БД.
    - Для отсутствующих выходов просто делает предикт заранее предобученной моделькой и пишет куда надо.
3. Штуку, которая берёт каждый отдельный класс с предыдущего этапа и делает поверх предикт предобученной тематической моделью.
    - Шаги работы таска можно по аналогии с предыдущими.

Пока хватит.

Разовые задачи, которые когда-то тоже переедут в пайплайн:
1. Обучить классификатор рубрик. 
    - Тут есть загвоздка. На ленте у нас результат не чистый из-за грязных меток, из-за страшного дисбаланса и так далее. На газете метки лучше, но сильный дисбаланс. Возможно адекватно будет делать классификатор `спорт / политика`, или `спорт / не спорт`, а затем "не спорт" ещё раз, но пока не важно. На выходе в общем должна быть одна штука, которую подгрузил, засунул текст и получил предикты.
2. Когда классификатор будет готов, надо будет ТМ поверх сделать.

**Comment by iggisv9t** [comment]
Из того, что уже готово, ниже ссылки. Это можно просто импортировать и упаковывать вы luigi таск. То есть б**о**льшая часть работы уже сделана.

Штука для препроцессинга здесь:
https://github.com/ods-ai-ml4sg/proj_news_viz/blob/master/nlp/news_viz/data/preprocessing_tools.py

Штука для тематических моделей здесь:
https://github.com/ods-ai-ml4sg/proj_news_viz/blob/master/nlp/notebooks/topic_models/separateTopics/lenta/extract_topics.py

**Comment by Avenon** [comment]
У меня первоначальный вариант пайплана как раз был такой: из необработанных файлов делалось преобразование и записывалось в postgres. Я уже потом прикрутил загрузку необработанных данных в БД, и перестроил таски с одной таблицы в другую. Я посмотрю, должен быть остаться первоначальный вариант. Если же не осталось, то переделать сущестующий, думаю не долго будет. Будет изначальный вариант: 1) Переодически опрос каталога на предмет получения новых необработанных файлов 2) Преобразование 3) Запись обработнного файла в processed

Я, правда, не очень понимаю, почему вернулись к такому подходу? Работающий постгресс ведь есть, работает, оставалось только скрапинг нормально переделать, чтобы он сразу в БД писал. Я не думаю, что это понизит порог входа, тем более бОльшая часть уже готова

**Comment by Avenon** [comment]
> Это можно просто импортировать и упаковывать вы luigi таск. То есть большая часть работы уже сделана.

Не просто сделана, но уже упакована в таски на луиджи, вот я делал: https://github.com/ods-ai-ml4sg/proj_news_viz/tree/master/data-flow-luigi/nlp/transform_data

Поэтому, к посту выше, нужно переписать все эти таски под файлы

**Comment by iggisv9t** [comment]
> Я, правда, не очень понимаю, почему вернулись к такому подходу? Работающий постгресс ведь есть, работает  
Потому что я пытался работать с твоим кодом по твоей инструкции. Было очень тяжко, я что-то правил по ходу, чтобы оно заводилось. Разные конфиги в разных местах. Всё в итоге запустилось, но до дела я так и не дошёл. Мало кто, кроме тебя сможет это дописать. Всё должно состоять из очень маленьких атомарных вещей, которые можно переделывать независимо друг от друга почти не зная контекст. То, что у нас сейчас есть под этот критерий не подходит. Надо либо очень сильно отрефакторить, либо вот спуститься до файликов.

**Comment by Avenon** [comment]
Там самое сложное это развернуть скриптами базу. Для простоты я могу сделать дамп структуры базы и выложить релизы. Будет проще.  Сам запуск пайплайна в одну строку в консоле делается.

**Comment by iggisv9t** [comment]
Две таски из трёх готовы и протестированы. Осталось подпилить чуть-чуть (там есть TODO, докстринги например) и доделать третью. 

https://github.com/ods-ai-ml4sg/proj_news_viz/tree/sv9t_pipeline/pipeline

**Comment by iggisv9t** [comment]
> Для простоты я могу сделать дамп структуры базы и выложить релизы.  
  
Это будет что надо. И пайплайн у тебя только небольшого рефакторинга требует. Но вот ту часть, которая занимается базой придётся в будущем распилить на более мелкие и простые куски. А пока постгру ставим на паузу.

**Comment by iggisv9t** [comment]
Ну что, модуль для TM сделан и протестирован. 26 дней не мог найти свободную минутку, потом за день его сделал. Теперь надо последний луиджи таск впилить. Работы на день осталось.

**Comment by vtrokhymenko** [comment]
@iggisv9t в #109 зарефакторил препроцессинг, используй лучше его, а то то что есть очень плохое (моя ошибка что не ответственно изначально сделал)

**Comment by iggisv9t** [comment]
На самом деле предполагается, что там можно втыкать внешний препроцессинг. Поэтому сначала ТМ таск допилю, а потом уже можно новый препроцессинг прилепить и качество отдельных кусков повышать независимо.

**Comment by iggisv9t** [comment]
Из того, что осталось доделать -- это функция для вытаскивания топ-слов по темам. Локально она у меня готова в ноутбучеке, но надо перенести в скрипт и впилить в пайплайн, чтобы сразу топ-слов рядом лежал в конце процесса.

Ну и документация.
Надо написать:
1. Как выполняется вся эта штука
2. Что нужно сделать заранее
3. Куда положить, какие каталоги создать заранее
4. Как будет выглядеть результат каждого этапа
5. Как его интерпретировать и рисовать

**Comment by iggisv9t** [comment]
Доки здесь.
https://github.com/ods-ai-ml4sg/proj_news_viz/wiki/Pipeline-инструкция-по-применению
