### ISSUE TITLE
Актуальный пример запуск скрэппера

### ISSUE THREAD

**Issue by serhio7** [ods-ai-ml4sg/proj_news_viz#73]
Добрый день!
Вижу что текущий ReadMe уже неактуальный. Можете подсказать как в текущей версии проекта запускать скрэппер?

**Comment by vtrokhymenko** [comment]
@iggisv9t сможешь помочь?

**Comment by iggisv9t** [comment]
Кажется, актуальный ридми лежит тут https://github.com/ods-ai-ml4sg/proj_news_viz/tree/master/scraping/newsbot
Самая актуальная информация у @Teoretic6 но он сейчас не участвует активно в проекте. Может быть, если накопятся вопросы, он ответит.

Вообще есть кусок, который делал @buriy и текущий ридми, кажется относится к нему. Но данные из этого скраппера мы так и не увидели. Замечательно будет, если кто-то возьмётся за чистку этой части проекта от "мёртвых" частей.

 Илья писал после этого отдельных пауков на каждый сайт, все новые данные из этих пауков.

**Comment by serhio7** [comment]
@iggisv9t вижу, спасибо. Осталось выяснить нюанс как scrapy установить корректно - потому что в лоб я получаю ошибку 
![image](https://user-images.githubusercontent.com/4029753/65897277-7348ce80-e39e-11e9-819f-00be2ade940f.png)

**Comment by iggisv9t** [comment]
Как на винду ставить -- не знаю. У меня под линуксом просто работало. Может быть на гитхабе scrapy есть ишью по этому поводу тоже.

**Comment by karelin** [comment]
Под анакондой scrapy на windows отлично ставится.

**Comment by buriy** [comment]
>Вообще есть кусок, который делал @buriy и текущий ридми, кажется относится к нему. Но данные из этого скраппера мы так и не увидели. Замечательно будет, если кто-то возьмётся за чистку этой части проекта от "мёртвых" частей.
У меня где-то на диске лежат данные от этого запуска, да, но их не очень много, надо просто его заново запустить (но наверное убрать те сайты, которые специализированными парсерами скачались). А результаты прошлого запуска с такой же архитектурой лежат тут:
https://github.com/buriy/russian-nlp-datasets/releases (за годы 2014 и 2015)
Индивидуальные скреперы лучше работают, так что, если не хотеть сделать вытаскивание одновременно с сотен и тысяч различных сайтов, то специализированный парсер его превзошёл. Но я не теряю надежды, что скачивание сотен и тысяч сайтов вернётся в план действий по проекту.
Я проверю, коммитал ли я версию с последними сохранениями.

**Comment by serhio7** [comment]
@karelin, спасибо! Действительно поставилось без проблем и заработало. Еще один вопрос - где можно указать директорию сохранения для газеты?
